# Generated by Django 4.2.4 on 2023-09-04 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Displayed in the selection form for the user', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=False, verbose_name='available for users?')),
                ('scraper_status', models.CharField(choices=[('AV', 'Available'), ('IP', 'In progress')], default='AV', editable=False, max_length=2, verbose_name='Scraper status')),
            ],
            options={
                'verbose_name': 'Cinema Provider',
                'verbose_name_plural': 'Cinema Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date_query', models.DateField(help_text='Scraper looks for data for this date')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinemaprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
