# Generated by Django 4.2.4 on 2023-09-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapertask',
            old_name='cinema',
            new_name='cinema_provider',
        ),
    ]
