# Generated by Django 4.2.4 on 2023-09-04 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_rename_cinema_scrapertask_cinema_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowtimeSeats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(verbose_name='Showtime datetime')),
                ('url', models.URLField(blank=True, verbose_name='Showtime page url')),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('all', models.PositiveIntegerField(verbose_name='All seats')),
                ('sold', models.PositiveIntegerField(verbose_name='Sold seats')),
                ('cinema_room', models.CharField(blank=True, max_length=255)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.movie')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.scrapertask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
