# Generated by Django 4.2.5 on 2023-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0004_showtimeseats_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaprovider',
            name='scraper_file',
            field=models.FilePathField(default='novocinemas.py', help_text='The file must be in the "scrapers" folder', path='/scrapers', recursive=True),
            preserve_default=False,
        ),
    ]
