# Generated by Django 4.2.5 on 2023-09-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_cinemaprovider_scraper_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtimeseats',
            options={'ordering': ['-created_on'], 'verbose_name': 'Showtime Seats', 'verbose_name_plural': 'Showtime Seats'},
        ),
        migrations.AddField(
            model_name='showtimeseats',
            name='type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Seats type'),
        ),
        migrations.AlterField(
            model_name='cinemaprovider',
            name='scraper_file',
            field=models.FilePathField(help_text='The file must be in the "scrapers" folder', match='.*\\.py$', path='scrapers', recursive=True),
        ),
    ]
