# Generated by Django 4.2.5 on 2023-09-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('cinemas', '0006_alter_showtimeseats_options_showtimeseats_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtimeseats',
            name='type',
        ),
        migrations.AddField(
            model_name='cinema',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='showtimeseats',
            name='area',
            field=models.CharField(blank=True, max_length=255, verbose_name='Seats area'),
        ),
        migrations.AlterField(
            model_name='showtimeseats',
            name='cinema_room',
            field=models.CharField(blank=True, max_length=255, verbose_name='Seats screen'),
        ),
    ]
