# Generated by Django 4.2.5 on 2023-09-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_remove_showtimeseats_type_cinema_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaprovider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
