# Generated by Django 4.2.5 on 2023-09-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_cinemaprovider_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaprovider',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
